ROWS = 25
COLS = 50
WIDTH_MULTIPLIER = 20
HEIGHT_MULTIPLIER = 20
WINDOW_WIDTH = COLS * WIDTH_MULTIPLIER #1000
WINDOW_HEIGHT = ROWS * HEIGHT_MULTIPLIER #500
NUM_OF_OBJECTS = 20
BACKGROUND_COLOR = (50, 205, 50)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREEN = (0, 255, 0)
SOLDIER_START_PLACE = (0,0)
SOLDIER_WIDTH = 2
SOLDIER_HEIGHT = 4
SOLDIER_WIDTH_PIXEL = 80
SOLDIER_HEIGHT_PIXEL = 80
BOMB_WIDTH_PIXEL = 3 * WIDTH_MULTIPLIER
BOMB_HEIGHT_PIXEL = 1 * HEIGHT_MULTIPLIER
BOMB_WIDTH = 3
BOMB_HEIGHT = 1
BOMB_COUNT = 20
FLAG_WIDTH = 4
FLAG_HEIGHT = 3
FLAG_WIDTH_PIXEL = 80
FLAG_HEIGHT_PIXEL = 80
GRASS_HEIGHT = 3 * HEIGHT_MULTIPLIER
GRASS_WIDTH = 3 * WIDTH_MULTIPLIER
FLAG_START_PLACE = (ROWS-FLAG_HEIGHT-1, COLS-FLAG_WIDTH)
SOLDIER = 's'
FLAG = 'f'
BOMB = 'b'
EMPTY = ' '
UP = 'up'
DOWN = 'down'
LEFT = 'left'
RIGHT = 'right'

FLAG_PATH = "flag.png"
SOLDIER_PATH = "soldier.png"
SOLDIER_NIGHT_PATH = "soldier_night.png"
BOMB_PATH = "bomb.png"
GRASS_PATH = "grass.png"

FONT_NAME = "Segoe UI"
LOSE_MESSAGE = "You Lost!"
LOSE_FONT_SIZE = int(0.15 * WINDOW_WIDTH)
LOSE_COLOR = BLACK
LOSE_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (LOSE_FONT_SIZE / 2))
WIN_MESSAGE = "You Won!"
WIN_FONT_SIZE = LOSE_FONT_SIZE
WIN_COLOR = (89, 89, 89)
WIN_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (WIN_FONT_SIZE / 2))

TOUCHING_FLAG = 2
TOUCHING_EMPTY = 1
TOUCHING_BOMB = 0

#save or load files (part 2)
LOAD = 0
SAVE = 1
COL_NUMBER = "number"
COL_SOLDIER = "soldier"
COL_BOMBS = "bombs"
COL_GRASS = "grass"